#!/bin/bash

recursive=false
depth=5
path=./data/
forms="jpg,jpeg,png,bmp"

while getopts ":r:l::p:" opt; do
	case $opt in
		l )
			depth=$OPTARG
			;;
		r )
			recursive=true
			;;
		p )
			path=$OPTARG
			;;
		\? )
			echo -e "\e[31mInvalid option -$OPTARG\e[0m" >&2
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	echo -e "\e[31mNo URL entered\e[0m" >&2
	exit 1
fi

URL=$1
echo -e "\e[32mDownloading $URL in $path\e[0m"
if [ "$recursive" == "true" ]; then
	wget -r -A "$forms" -l "$depth" -P "$path" "$URL"
else
	wget -A "$forms" -P "$path" "$URL"
fi